### ISSUE TITLE
Files for various terminals

### ISSUE THREAD

**Issue by Efreak** [gbgabo/wildberries#1] opened 2024-05-31 11:45 UTC
For Windows Terminal, you can use the following in your config.json: 

```javascript
{
  "name": "Wildberries",
  "background": "#1902e",
  "foreground": "#ffe82",
  "black": "#151515",
  "blue": "#90048",
  "cyan": "#0ff40",
  "green": "#f4cc53",
  "purple": "#0ffff",
  "red": "#c79bff",
  "white": "#0ffb7",
  "yellow": "#d0d0d0",
  "brightBlack": "#505050",
  "brightBlue": "#90048",
  "brightCyan": "#0ff40",
  "brightGreen": "#f4cc53",
  "brightPurple": "#0ffff",
  "brightRed": "#c79bff",
  "brightWhite": "#0ffb7",
  "brightYellow": "#f5f5f5"
}
```

To add "free" support for a massive list of software, you can also submit to https://github.com/tinted-theming/home

**Comment by gbgabo** [comment] 2024-08-22 00:03
Greetings, @Efreak!

Firstly, sorry for the lack of return for such a long time. Not only I got aware of your issue some weeks ago, but I also have been working on adding your port.

Some weeks ago I mistakenly had pushed to main a half baked page with your snippet. [Now It's fully written an available](https://www.wildberries.style/windows-terminal), and with a new UI to also include a mention of your contribution (Tell me in any case your prefer me to remove it).

Thanks a lot for this actual first direct external contribution on the project! 🎉🎉 I haven't been in a windows system to recreate the port so there isn't a screenshot on the page currently. Thanks for the tinted-theming reference too! I'll definitely save time to submit there.

btw, the repo you originally open the issue is now not maintained, I've ported the site to Astro so I'm moving it to there (I mean here!)  and properly attributing your contribution, since even the changes were already being added from there (here) too.

**Closed as completed** 2024-10-17 05:19 UTC
